SharebookBR/sharebook-backend

ShareBook/ShareBook.Api/Controllers/AccountController.cs, ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Helper/Crypto/Hash.cs, ShareBook/ShareBook.Helper/Crypto/Salt.cs, ShareBook/ShareBook.Helper/ShareBook.Helper.csproj, ShareBook/ShareBook.Repository/Mapping/UserMap.cs, ShareBook/ShareBook.Repository/Migrations/20180524102641_PasswordSalt.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20180524102641_PasswordSalt.cs, ShareBook/ShareBook.Service/User/IUserService.cs, ShareBook/ShareBook.Service/User/UserService.cs
- Criação de classe Hash em Sharebook.Helper
- Criação de classe Salt em Sharebook.Helper
- Alterados métodos GetByEmailAndPassword e Insert em ShareBook.Service.UserService
=> Criando criptografia de senha para autenticação de usuário

ShareBook/ShareBook.Api/Controllers/AccountController.cs, ShareBook/ShareBook.Api/Controllers/BaseController.cs, ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/appsettings.json, ShareBook/ShareBook.Domain/Common/Result.cs, ShareBook/ShareBook.Domain/LogEntry.cs, ShareBook/ShareBook.Repository/ApplicationDbContext.cs, ShareBook/ShareBook.Repository/LoggingContext.cs, ShareBook/ShareBook.Repository/Mapping/LogEntryMap.cs, ShareBook/ShareBook.Repository/Migrations/20180528205801_ChangeLogEntry_HoldOnlyValuesChanges.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20180528205801_ChangeLogEntry_HoldOnlyValuesChanges.cs, ShareBook/ShareBook.Repository/ShareBook.Repository.csproj, ShareBook/ShareBook.Service/Generic/BaseService.cs, ShareBook/ShareBook.Service/Generic/IBaseService.cs
- Corrigindo erro no build por causa do log
- Correção/melhoria do log: antes ele estava sempre mostrando os mesmos valores para o original e o updated. Agora ele só possuí um campo. Na inserção e na exclusão, esse campo irá ter o json completo da entidade no momento. No caso de alteração, ele terá um json comparativo entre os campos alterados, com valores originais e novos.
- Aumentando o tempo do token para 1h
- Retornando o Result para o método de Delete (caso queira rodar algum tipo de validação)
- Criando endPoints para update e delete de livro
- Movendo os métodos básicos e padrões de CRUD para o baseController
=> Melhorias e correções no log, nos controllers. aumento do tempo do token

ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Domain/Validators/UserValidator.cs, ShareBook/ShareBook.Repository/Mapping/UserMap.cs, ShareBook/ShareBook.Repository/Migrations/20180605165917_AlterTables.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20180605165917_AlterTables.cs, ShareBook/ShareBook.Service/Generic/BaseService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/ShareBook.Test.Unit/Services/UserServiceTests.cs, ShareBook/ShareBook.Test.Unit/Validators/UserValidatorTests.cs
DoD
- Cadastrar dados do usuário
Nome 
Email
Senha
Url do linkedin
CEP
=> Registrar usuário com nome, email, senha, url do linkedin, cep

ShareBook/ShareBook.Api/ShareBook.Api.csproj
Adicionando pacote que eh necessário!
=> Added package Microsoft.AspNetCore.Http.Abstractions

ShareBook/ShareBook.Api/AutoMapper/ViewModelToDomainMappingProfile.cs, ShareBook/ShareBook.Api/Controllers/AccountController.cs, ShareBook/ShareBook.Api/ViewModels/UpdateUserVM.cs, ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Repository/LoggingContext.cs, ShareBook/ShareBook.Service/Generic/BaseService.cs, ShareBook/ShareBook.Service/User/IUserService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/ShareBook.Test.Unit/Services/UserServiceTests.cs
10 - EU, ENQUANTO RODRIGO/ WALTER, PRECISO MUDAR MEUS DADOS CADASTRADOS NO SISTEMA.
Corrigido bug em loggingContext
=> feature #10 do trello

ShareBook/ShareBook.Api/Controllers/AccountController.cs, ShareBook/ShareBook.Api/ViewModels/UpdateUserVM.cs, ShareBook/ShareBook.Service/User/IUserService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/ShareBook.Test.Unit/Services/UserServiceTests.cs
Agora a atualização do usuário terá que enviar o id
=> Corrigindo Bug atualizar usuário 

ShareBook/ShareBook.Test.Unit/Services/EmailTemplateTests.cs
Validação apenas dos valores a serem modificados e não do template completo (devido a quebra de linhas no servidor de produção)
=> Ajuste no teste de template de e-mail

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/Startup.cs
…odando seed se for stage ou development
=> Colocando filtro de autorização nos endpoints do book para adm 

ShareBook/ShareBook.Domain/Book.cs, ShareBook/ShareBook.Repository/Repository/Book/BookRepository.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/Email/Templates/BookDonatedTemplate.html
Corrigindo envio de e-mail ao solicitar um livro e corrigindo select  de livros doados ou não
=>  envio de e-mail ao solicitar um livro / select  de livros doados ou não

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs, ShareBook/ShareBook.Service/Email/Templates/BookDonatedTemplate.html, ShareBook/ShareBook.Service/Email/Templates/BookRequestedTemplate.html
- Ajustando espaços e erro ortográfico nos e-mails
- #TK-11 Criando o método de FullSearch para livros
- Refactory pare reuso de código
- Os métodos ByTitle e ByAuthor tinham o código repetido, sendo a diferença entre eles apenas o critério da busca. Com a inclusão de mais um método (FullSearch), passamos a ter o mesmo código repetido 3 vezes. Logo, fiz um refactory onde temos agora o mesmo código apenas uma vez e este novo método (private) recebe o critério da busca que será diferente.
=> #TK-11, pequeno refactory e acertos ortográficos nos e-mails

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/ViewModels/RequestBookVM.cs, ShareBook/ShareBook.Domain/BookUser.cs, ShareBook/ShareBook.Repository/Mapping/BookUserMap.cs, ShareBook/ShareBook.Repository/Migrations/20180906200545_AlterTables_Reason.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20180906200545_AlterTables_Reason.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/BookUser/IBookUserService.cs, ShareBook/ShareBook.Test.Unit/Services/BookUserServiceTests.cs
Boas perguntas pra incentivar o INTERESSADO a escrever um bom texto:
Fale um pouco sobre você.
Por que esse livro é importante?
Planeja doar?
Obs: Pode ser tudo no mesmo campo.
=> INTERESSADO INFORMA MOTIVO.

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/ViewModels/ApproveBookVM.cs, ShareBook/ShareBook.Domain/Book.cs, ShareBook/ShareBook.Repository/Migrations/20181126220912_ChooseDateForBooks.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20181126220912_ChooseDateForBooks.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/Email/Templates/BookApprovedTemplate.html
Trello: https://trello.com/c/NQxE9OOo
CRITÉRIOS DE ACEITE.
- DATA DE DECISÃO = DATA APROVAÇÃO + 5 DIAS.
- AVISO APÓS O LIVRO SER APROVADO.
- PODE IR JUNTO NO MESMO EMAIL DE APROVAÇÃO.
- PRECISA DEMONSTRAR IMPORTÂNCIA DESSA DATA DE DECISÃO PORQUE TODOS OS INTERESSADOS VÃO ESPERAR POR ELA. MUITO IMPORTANTE!!! NÃO PODE ATRASAR!!!
=> 20 - EU, ENQUANTO RODRIGO DOADOR, PRECISO SER INFORMADO DA 'DATA DE DECISÃO' DE FORMA A AUMENTAR MEU ENGAJAMENTO.

ShareBook/ShareBook.Api/appsettings.Development.json, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/BookUser/IBookUsersEmailService.cs, ShareBook/ShareBook.Service/Email/EmailService.cs, ShareBook/ShareBook.Service/Email/Templates/BookNoticeDonorTemplate.html, ShareBook/ShareBook.Service/ShareBook.Service.csproj
=> PR Implementação da Estoria 21 

ShareBook/ShareBook.Api/Startup.cs, ShareBook/ShareBook.Service/Book/BookService.cs
* Corrigindo problema de CreationDate null no retorno dos livros
* Configurando para ignorar os campos null no retorno do Json
=> Corrigindo CreationDate sempre com hora atual no retorno de livros

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Service/Book/BookService.cs
Eu sei que não é o ideal. Mas precisamos entregar as estórias 19, 20 e 21.
Sei que temos pendências, que não são de hoje. Tem meu compromisso de que elas não vão cair no esquecimento. Todas foram endereçadas por ISSUE aqui no github e por TAREFA no trello.
Conto com a compreensão de vocês com meu senso de urgência.
=> Apagando incêndio.

ShareBook/ShareBook.Service/Book/BookService.cs
Pra ajudar o Antero a fechar a estória 22.
=> Incluir ChooseDate visível pro front.

ShareBook/ShareBook.Api/Controllers/AccountController.cs, ShareBook/ShareBook.Api/ViewModels/ChangeUserPasswordByEmailAndHashCodeVM.cs, ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Service/User/IUserService.cs, ShareBook/ShareBook.Service/User/UserService.cs
Nesse PR  removi a validação por e-mail , agora é só por hashcode. Além disso estou gerando o hashcode a partir de um Guid =)
=> Bug - Esqueci a senha

ShareBook/ShareBook.Api/appsettings.Development.json, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/Email/Templates/BookNoticeDonorTemplate.html
Melhoria solicitado pelo @wantero para indicar no e-mail que é enviado ao doador do livro quando existe um novo interessado no seu livro.
Foi incluído o campo de **Local de destino** .
=> Atualização de e-mail de aviso ao doador do livro

ShareBook/ShareBook.Service/Book/BookService.cs
Atualização do choose date na edição do livro.
Pessoal por favor analisar esse PR. 
Tem por objetivo evitar que o chooseDate seja modificado na edição do livro.
Na verdade o problema acontecia devido ao mapeamento que tem da VM para entidade como o chooseDate não é uma propriedade vinda do front então era mapeada para null.
o que fiz foi, antes de atualizar, buscar o livro no banco para re-hidratar o objeto com somente os dados que devem ser atualizados.  então o chooseDate não foi passado do objeto que vem do front para o objeto consultado na base .
=> Fix bug  #196

ShareBook/ShareBook.Repository/Mapping/JobHistoryMap.cs, ShareBook/ShareBook.Repository/Migrations/20190124201920_JobHistoryDetailsMaxLength.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20190124201920_JobHistoryDetailsMaxLength.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/Sharebook.Jobs/Jobs/2 - LateDonationNotification.cs
=> Job novo. Sempre tem uns ajustezinhos do dia seguinte. :-)

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/ViewModels/UserVM.cs, ShareBook/ShareBook.Domain/Book.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs
- Doador, facilitador e ganhador.
- Pra ser usado na tela de gerenciar livros. Ao clicar num usuário abre a modal com detalhes dos contatos em 3 colunas.
- Com isso, enfim, finaliza a parte de back na estória 30.
=> Novo endpoint com os principais usuários numa doação.

ShareBook/ShareBook.Service/Book/BookService.cs
=> Fix: atualização de imagem do livro

ShareBook/ShareBook.Api/AutoMapper/DomainToViewModelMappingProfile.cs, ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/ViewModels/RequestersListVM.cs, ShareBook/ShareBook.Domain/BookUser.cs, ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Repository/Mapping/BookUserMap.cs, ShareBook/ShareBook.Repository/Mapping/UserMap.cs, ShareBook/ShareBook.Repository/Migrations/20190215221423_NickName.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20190215221423_NickName.cs, ShareBook/ShareBook.Repository/Migrations/20190215221758_NickName64.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20190215221758_NickName64.cs, ShareBook/ShareBook.Repository/ShareBookSeeder.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/BookUser/IBookUserService.cs, ShareBook/ShareBook.Service/BookUser/IBookUsersEmailService.cs
Estou mandando essa PR pra dar visibilidade. Por favor não aprovem ainda.
Preciso de ajuda na parte de colocar o apelido.
DomainToViewModelMappingProfile.cs  >> linha 45
=> Novo endpoint com a lista de interessados.

ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs
@raffacabofrio  dá uma olhada por favor, falta pouco para conseguirmos!
=> Atualizando de Book.User para BookUser.User

ShareBook/ShareBook.Api/ShareBook.Api.csproj, ShareBook/ShareBook.Api/Startup.cs
Pessoal esse pull request é para dar opções à vocês sobre o health check, nesse caso utilizei para fazer conexão com o banco de dados e devolver healthy se estiver tudo ok, ou unhealthy se estiver com probelmas de conexão. Caso gostarem posso utilizar, essa lib para outros serviços e mais diagnosticos, oque acham ?
=> Health check Added

ShareBook/ShareBook.Service/Book/BookService.cs
Não sei pra vcs, mas comigo eh assim. Acho MUITO mais amigável ler e dar manutenção uma consulta com LINQ.
Amanhã faço o do 'MyRequests' também.
=>  'Minhas doações' ordenando por CreationDate desc.

ShareBook/Dockerfile, ShareBook/ShareBook.Api/Dockerfile, docker-compose.yml
Agora podemos ter um container da nossa api. Basta ter o docker instalado e digitar o comando:
docker-compose up -d --build
e acessar a url https:127.0.0.1:8181/hc para ver se a API subiu!
=> Criação do docker file e docker compose 

ShareBook/ShareBook.Api/AutoMapper/ViewModelToDomainMappingProfile.cs, ShareBook/ShareBook.Api/Configuration/ServiceRepositoryCollectionExtensions.cs, ShareBook/ShareBook.Api/Controllers/NotificationController.cs, ShareBook/ShareBook.Api/Startup.cs, ShareBook/ShareBook.Api/ViewModels/NotificationOnesignalVM.cs, ShareBook/ShareBook.Api/appsettings.Development.json, ShareBook/ShareBook.Domain/Enums/TypeSegments.cs, ShareBook/ShareBook.Domain/NotificationOnesignal.cs, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/Notification/INotificationService.cs, ShareBook/ShareBook.Service/Notification/NotificationService.cs, ShareBook/ShareBook.Service/Notification/NotificationSettings.cs, ShareBook/ShareBook.Service/ShareBook.Service.csproj
Só foi implementando até agora dois tipo de notificação. A primeira para o dono do livro vai ser notificado quando alguém quiser seu livro e a outra é para o usuário que solicitou o livro. Mas como a implementação está _"genérica"_ pode ser usado para qualquer tipo de notificação
=> Criando sistema de notificação 

ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs
Melhorando título da notificação para o dono do livro
=> Melhorando título da notificação para o dono do livro

ShareBook/ShareBook.Api/ViewModels/RegisterUserVM.cs, ShareBook/ShareBook.Api/ViewModels/UpdateUserVM.cs, ShareBook/ShareBook.Api/ViewModels/UserVM.cs, ShareBook/ShareBook.Domain/User.cs, ShareBook/ShareBook.Repository/Mapping/UserMap.cs, ShareBook/ShareBook.Repository/Migrations/20190723200511_AddAllowSendingEmailColumn.Designer.cs, ShareBook/ShareBook.Repository/Migrations/20190723200511_AddAllowSendingEmailColumn.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/Email/EmailService.cs, ShareBook/ShareBook.Service/Email/IEmailService.cs, ShareBook/ShareBook.Service/User/UserEmailService.cs
A new column was added to `Users` table in order to control emails flow. Based on this flag, the user can opt in or out for receiving messages and notifications through email.
=> Add user emails flag

ShareBook/ShareBook.Api/ShareBook.Api.csproj, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/Muambator/IMuambatorService.cs, ShareBook/ShareBook.Service/Muambator/MuambatorService.cs
Pessoal podem ser exigentes nesse code review. Não estou seguro se segui um bom caminho. Em especial ao uso de dynamic. Estou usando MAC e comigo o JSON não estava sendo deserializado pra um tipo de jeito nenhum. :/
Obrigado.
=> Adiciona título do livro e mais emails no muambator.

ShareBook/ShareBook.Service/Email/Templates/ContactUsNotificationTemplate.html, ShareBook/ShareBook.Service/Email/Templates/ContactUsTemplate.html
Raffa, dá uma olhada se o tamanho ficou bom.
=> - Ajusta tamanho da imagem original [Fale Conosco]

ShareBook/ShareBook.Domain/Validators/UserValidator.cs, ShareBook/ShareBook.Service/User/UserService.cs
Validando tamanho da senha.
Correção de lógica na rotina de verificação de brute force login.
=> Validando tamanho da senha.

ShareBook/ShareBook.Api/Program.cs
Explicitando erros de compilação, para que na página inicial caso não consiga ser compilado, conseguimos ver o erro
=> Explicitando erros

ShareBook/ShareBook.Api/Startup.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Test.Unit/Mocks/BookMock.cs, ShareBook/ShareBook.Test.Unit/Services/BookUserServiceTests.cs
Imagens estão quebradas no mobile. Max suspeita que com cors elas vão voltar a funcionar. Vamos ver.
=> Habilita cors para imagens.

ShareBook/ShareBook.Api/Controllers/OperationsController.cs, ShareBook/ShareBook.Api/Middleware/ExceptionHandlerMiddleware.cs, ShareBook/ShareBook.Service/Book/BookService.cs
Pra corrigir esse erro eu acabei tendo que corrigir vários outros pequenos problemas.
=> Solicitar livro funcionando com core 3.1

ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/Controllers/OperationsController.cs, ShareBook/ShareBook.Api/ViewModels/EmailTestVM.cs, ShareBook/ShareBook.Domain/Book.cs, ShareBook/ShareBook.Domain/Common/Result.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs, ShareBook/ShareBook.Service/Email/EmailService.cs, ShareBook/ShareBook.Service/Email/IEmailService.cs
Essa pr corrige um pequeno bug da tarefa de status centralizado, pra gente poder começar o front.
E também inclui um novo endpoint pra gente poder testar email. Apenas adms vão ter acesso.
=> Status centralizado + teste de email

ShareBook/ShareBook.Api/Configuration/ServiceRepositoryCollectionExtensions.cs, ShareBook/ShareBook.Api/Startup.cs, ShareBook/ShareBook.Api/appsettings.Development.json, ShareBook/ShareBook.Domain/Enums/JobInterval.cs, ShareBook/ShareBook.Service/AWSSQS/AWSSQSService.cs, ShareBook/ShareBook.Service/AWSSQS/AWSSQSSettings.cs, ShareBook/ShareBook.Service/AWSSQS/Dto/AWSSQSMessageNewBookNotify.cs, ShareBook/ShareBook.Service/AWSSQS/Dto/AWSSQSMessageNewBookNotifyRequest.cs, ShareBook/ShareBook.Service/AWSSQS/Dto/AWSSQSMessageNewBookNotifyResponse.cs, ShareBook/ShareBook.Service/AWSSQS/IAWSSQSService.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/Book/IBooksEmailService.cs, ShareBook/ShareBook.Service/Email/Templates/NewBookNotifyTemplate.html, ShareBook/ShareBook.Service/ShareBook.Service.csproj, ShareBook/ShareBook.Service/User/IUserService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/Sharebook.Jobs/Executor/JobExecutor.cs, ShareBook/Sharebook.Jobs/Jobs/4 - NewBookNotify.cs, ShareBook/Sharebook.Jobs/Jobs/GenericJob.cs
Olá, senhores. Tudo bem? Segue um novo PR :D
**Tarefa Trello**: https://trello.com/c/Un61uMaG/161-notifica-novo-livro-para-poss%C3%ADveis-interessados
**Descrição**: Foi implementado um serviço para que quando um livro for aprovado seja enviado um e-mail para possíveis usuários interessados, ou seja, para usuários que já solicitaram algum livro da mesma categoria do novo livro. Esse novo serviço faz uso da **AWS SQS** para orquestrar as mensagens de envio de email. 
**Funcionamento básico**: Assim que um livro é aprovado, é chamado um serviço que envia as mensagens formatadas para AWS SQS com o html do e-mail e uma lista de usuários para os quais o e-mail deve ser enviado. Depois de tempos em tempos um Job scheduler é invocado para ler as mensagens da AWS SQS e então enviar os e-mails.
No …
=> Implementação de notificação, usando AWS SQS, para possíveis usuários interessados no novo livro

ShareBook/ShareBook.Api/AutoMapper/DomainToViewModelMappingProfile.cs, ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/Middleware/ExceptionHandlerMiddleware.cs, ShareBook/ShareBook.Api/Startup.cs, ShareBook/ShareBook.Api/ViewModels/BooksVM.cs, ShareBook/ShareBook.Repository/ShareBookSeeder.cs, ShareBook/ShareBook.Service/AWSSQS/AWSSQSService.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/User/UserService.cs
Durante a implementação do front, foi fazendo alguns pequenos ajustes pra nosso app funcionar redondo.
=> Ajustes para o status único.

ShareBook/ShareBook.Api/AutoMapper/DomainToViewModelMappingProfile.cs, ShareBook/ShareBook.Api/Controllers/BookController.cs, ShareBook/ShareBook.Api/ViewModels/BooksVM.cs, ShareBook/ShareBook.Api/appsettings.Stage.json, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs
- GET /api/Book/Top15NewBooks
- GET /api/Book/Random15Books 
- GET /api/Book/Title/{title}/{page}/{items} 
- GET /api/Book/Author/{author}/{page}/{items} 
- GET /api/Book/Category/{categoryId}/{page}/{items} 
Obs. Aproveitei que estava com a mão na massa e renomeei
- ANTES: GET /api/Book/Top15NewBooks
- DEPOIS: GET /api/Book/AvailableBooks
=> Resolvendo o problema de segurança que persistiu em alguns endpoints.

ShareBook/ShareBook.Api/AutoMapper/DomainToViewModelMappingProfile.cs, ShareBook/ShareBook.Api/ShareBook.Api.csproj, ShareBook/ShareBook.Api/appsettings.Development.json, ShareBook/ShareBook.Api/appsettings.Stage.json, ShareBook/ShareBook.Domain/Enums/JobInterval.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/Email/Templates/NewBookNotifyTemplate.html, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/Sharebook.Jobs/Executor/JobExecutor.cs, ShareBook/Sharebook.Jobs/Jobs/4 - NewBookNotify.cs, ShareBook/Sharebook.Jobs/Jobs/GenericJob.cs, ShareBook/Sharebook.Jobs/Sharebook.Jobs.csproj
Fiz o QA e esses ajustes finais. Tudo pronto pra gente promover pra produção. :D
=> Pequenos ajustes na notificação de novo livro.

ShareBook/ShareBook.Api/Controllers/OperationsController.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/Book/IBooksEmailService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs, ShareBook/ShareBook.Service/ContactUs/ContactUsService.cs, ShareBook/ShareBook.Service/Email/EmailService.cs, ShareBook/ShareBook.Service/Email/IEmailService.cs, ShareBook/ShareBook.Service/Email/Templates/NewBookNotifyTemplate.html, ShareBook/ShareBook.Service/User/IUserEmailService.cs, ShareBook/ShareBook.Service/User/UserEmailService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/Sharebook.Jobs/Jobs/2 - LateDonationNotification.cs, ShareBook/Sharebook.Jobs/Jobs/4 - NewBookNotify.cs, ShareBook/Sharebook.Jobs/Jobs/GenericJob.cs
A gente tinha intenção de usar o conceito de "fire and forget" em alguns métodos assíncronos. A intenção era boa. Mas infelizmente não funcionou. Eventualmente cerca de 30% dos métodos assíncronos "morriam" antes de terminar seu trabalho.
Creio que tenha a ver com o garbage collector. Tendo em vista que o processo principal finalizou, pra todos os efeitos esse processo assíncrono parecia orfão. E eventualmente o garbage colector matava ele. 
Fiz uma validação em dev. Coloquei Wait() em todos os métodos assíncronos. E obtive 100% de aproveitamento. Alguns endpoints ficaram um pouco mais lento. Mas acho que vale a pena.
=> Resolve alguns problemas no job.

ShareBook/ShareBook.Api/AutoMapper/DomainToViewModelMappingProfile.cs, ShareBook/ShareBook.Api/ViewModels/MyBooksRequestsVM.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/BookUser/BookUserService.cs
Obs: Tive o cuidado para evitar que um usuário veja coisas que não pode.
=> Código de rastreio e status da doação no endpoint Meus Pedidos.

ShareBook/ShareBook.Service/Book/BookService.cs
Essa é bem simples. Nem precisa revisar. Só aprova sem ver kkk (humor)
=> Ordenar livros na home por data decrescente.

README.md
=> Update Readme (dotnet 6)

README.md
Update readme - (spelling corrections)
=> Update readme - (spelling corrections)

ShareBook/ShareBook.Api/Dockerfile, ShareBook/docker-compose.yml
Update Dockerfile and docker-compose to dotnet 6!
=> Update Dockerfile and docker-compose to dotnet 6!

ShareBook/ShareBook.Domain/Enums/BookStatus.cs, ShareBook/ShareBook.Domain/Enums/BookType.cs, ShareBook/ShareBook.Domain/Enums/DonationStatus.cs, ShareBook/ShareBook.Domain/Enums/FreightOption.cs, ShareBook/ShareBook.Domain/ShareBook.Domain.csproj
Remove/Migrate Newtonsoft to System.Text.Json
Note: This is danger, please analyse carefully each corner of application.
=> Remove/Migrate Newtonsoft to System.Text.Json

ShareBook/ShareBook.Service/Meetup/MeetupService.cs
Adiciona verificação para o caso de não haver nenhum título similar no dicionário.
=> Correção para falha ao buscar Meetup

ShareBook/ShareBook.Repository/ShareBookSeeder.cs
Adiciona as meetups no ShareBookSeeder
=> Add Meetup Seed

ShareBook/ShareBook.Api/Controllers/MeetupController.cs
Alteração para trazer os meetups por página e com tamanho da página dinâmico.
=> Retornar meetup com paginação dinamica

ShareBook/ShareBook.Api/Controllers/OperationsController.cs, ShareBook/ShareBook.Repository/Repository/Generic/RepositoryGeneric.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Book/BooksEmailService.cs, ShareBook/ShareBook.Service/Book/IBookService.cs, ShareBook/ShareBook.Service/Meetup/IMeetupService.cs, ShareBook/ShareBook.Service/Meetup/MeetupService.cs, ShareBook/ShareBook.Service/Muambator/MuambatorService.cs, ShareBook/ShareBook.Service/User/UserEmailService.cs, ShareBook/ShareBook.Service/User/UserService.cs, ShareBook/ShareBook.Test.Unit/Helpers/HelperTests.cs, ShareBook/ShareBook.Test.Unit/Services/EmailTemplateTests.cs, ShareBook/Sharebook.Jobs/Executor/IJobExecutor.cs, ShareBook/Sharebook.Jobs/Executor/JobExecutor.cs, ShareBook/Sharebook.Jobs/Jobs/0 - CancelAbandonedDonations.cs, ShareBook/Sharebook.Jobs/Jobs/1 - ChooseDateReminder.cs, ShareBook/Sharebook.Jobs/Jobs/2 - LateDonationNotification.cs, ShareBook/Sharebook.Jobs/Jobs/3 - RemoveBookFromShowcase.cs, ShareBook/Sharebook.Jobs/Jobs/4 - MeetupSearch.cs, ShareBook/Sharebook.Jobs/Jobs/5 - NewBookGetInterestedUsers.cs, ShareBook/Sharebook.Jobs/Jobs/6 - MailSupressListUpdate.cs, ShareBook/Sharebook.Jobs/Jobs/7 - MailSender.cs, ShareBook/Sharebook.Jobs/Jobs/GenericJob.cs, ShareBook/Sharebook.Jobs/Jobs/IJob.cs
The changes are made based on [.NET AsyncGuidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md). 
- Turning all jobs as async
- Got rid some warnings
- Getting rid `.Result`
- Adding some `TODO` comments for next improvements
=> Turning all jobs as async and async/await improvements

ShareBook/ShareBook.Api/Middleware/ExceptionHandlerMiddleware.cs, ShareBook/ShareBook.Domain/Exceptions/AwsSqsDisabledException.cs, ShareBook/ShareBook.Domain/Exceptions/MeetupDisabledException.cs, ShareBook/ShareBook.Helper/ShareBook.Helper.csproj, ShareBook/ShareBook.Repository/ApplicationDbContext.cs, ShareBook/ShareBook.Service/Book/BookService.cs, ShareBook/ShareBook.Service/Email/EmailService.cs, ShareBook/ShareBook.Service/Meetup/MeetupService.cs, ShareBook/ShareBook.Test.Unit/Services/BookUserServiceTests.cs, ShareBook/Sharebook.Jobs/Jobs/5 - NewBookGetInterestedUsers.cs
Before: 19 warnings
After: 10 warnings
**Note:  Should we create a database migration because the change at `ApplicationDbContext.OnModelCreating` ?**
=> Getting rid some warnings
