SharebookBR/sharebook-backend

- ShareBook/ShareBook.Api/Controllers/AccountController.cs
- ShareBook/ShareBook.Api/Controllers/BaseController.cs
- ShareBook/ShareBook.Api/Controllers/BookController.cs
- ShareBook/ShareBook.Api/Filters/GetClaimsFilter.cs
- ShareBook/ShareBook.Api/Startup.cs
- ShareBook/ShareBook.Domain/Book.cs
- ShareBook/ShareBook.Domain/Common/BaseEntity.cs
- ShareBook/ShareBook.Domain/LogEntry.cs
- ShareBook/ShareBook.Domain/User.cs
- ShareBook/ShareBook.Repository/ApplicationDbContext.cs
- ShareBook/ShareBook.Repository/Infra/CrossCutting/Identity/ApplicationSignInManager.cs
- ShareBook/ShareBook.Repository/LoggingContext.cs
- ShareBook/ShareBook.Repository/Mapping/LogEntryMap.cs
- ShareBook/ShareBook.Repository/Migrations/20180528120526_AddLogEntries.Designer.cs
- ShareBook/ShareBook.Repository/Migrations/20180528120526_AddLogEntries.cs
- ShareBook/ShareBook.Repository/Migrations/20180528134226_ChangeLogEntries_UserIdNull.Designer.cs
- ShareBook/ShareBook.Repository/Migrations/20180528134226_ChangeLogEntries_UserIdNull.cs
Agora as entidades devem herdar da BaseEntity. Dessa forma, a propriedade ID não é mais necessária de ser colocada na entidade.
Toda vez que rolar um SaveChanges a aplicação irá verificar todas as entidades inseridas, modificadas ou excluídas e irá gerar um log com a informação.
Os controllers devem herdar do BaseController. Hoje, ele só define um Filter que irá colocar o usuário do token na Thread.
Caso o CRUD seja executado por um usuário logado, o log irá registrar a alteração sob aquele usuário. Caso contrário, irá inserir null no campo.
> Include CRUD log

- ShareBook/ShareBook.Domain/User.cs
- ShareBook/ShareBook.Service/User/UserService.cs
- ShareBook/ShareBook.Test.Unit/Services/UserServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Validators/UserValidatorTests.cs
Não aceitar senhas "fracas".
critérios de aceite.
- deve ter pelo menos um caracter UPPERCASE.
- deve ter no mínimo 8 caracteres;
- deve ter pelo menos um caracter numérico.
> Criando mecanismo para senha forte

- ShareBook/ShareBook.Api/Controllers/AccountController.cs
- ShareBook/ShareBook.Api/ViewModels/ForgotMyPasswordVM.cs
Esta mudança visa arrumar o bug #167, movendo o parâmetro de email de recuperação de senha da URL para o corpo da requisição. Dessa forma, conseguiremos incluir emails mais complexos (p. ex, com sinal "+" no endereço).
> email para recuperação de senha no corpo do POST

- ShareBook/ShareBook.Api/Controllers/BookController.cs
Causa: Alguns endpoints devolviam o uma coleção de objetos que eventualmente poderia ser recursiva. Por conta disso o parser newtonsoft falhava. Tal coleção desprezada pelo front, que se preocupa apenas se a operação foi concluída com sucesso ou não.
Solução: Esses endpoints foram simplificados pra retornar um result. Sem coleção de objetos. Dentro do padrão que o front espera.
POST /api/book
PUT /api/book/[BOOK_ID]
> Resolve o problema de alguns requests sem resposta.

- ShareBook/ShareBook.Api/Controllers/CategoryController.cs
There is a need of increasing the number of categories per page. By overriding `PagedList` method on `CategoryController`, we are able to increase the number of items per page to 50, solving the issue of bringing only 15 items at a time.
> Issue #267 - Increasing Categories Search Size

- ShareBook/ShareBook.Api/Configuration/ServiceRepositoryCollectionExtensions.cs
- ShareBook/ShareBook.Api/Controllers/BookController.cs
- ShareBook/ShareBook.Api/ShareBook.Api.csproj
- ShareBook/ShareBook.Api/Startup.cs
- ShareBook/ShareBook.Api/appsettings.json
- ShareBook/ShareBook.Domain/ShareBook.Domain.csproj
- ShareBook/ShareBook.Repository/ShareBook.Infra.Data.csproj
- ShareBook/ShareBook.Service/BookUser/BookUserService.cs
- ShareBook/ShareBook.Service/Muambator/IMuambatorService.cs
- ShareBook/ShareBook.Service/Muambator/MuambatorConfigurator.cs
- ShareBook/ShareBook.Service/Muambator/MuambatorDTO.cs
- ShareBook/ShareBook.Service/Muambator/MuambatorService.cs
- ShareBook/ShareBook.Service/ShareBook.Service.csproj
- ShareBook/ShareBook.Test.Unit/Services/BookServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Services/BookUserServiceTests.cs
- ShareBook/ShareBook.Tests.BDD/ShareBook.Tests.BDD.csproj
Development of service which consumes the Muambator service to create a notification about the tracked package.
> Implentation of Muambator Service

- ShareBook/ShareBook.Api/Controllers/BookController.cs
- ShareBook/ShareBook.Service/Book/BookService.cs
- ShareBook/ShareBook.Service/Book/BooksEmailService.cs
- ShareBook/ShareBook.Service/Book/IBookService.cs
- ShareBook/ShareBook.Service/Book/IBooksEmailService.cs
- ShareBook/ShareBook.Service/Email/Templates/BookCanceledTemplate.html
- ShareBook/ShareBook.Service/Email/Templates/BookReceivedTemplate.html
- ShareBook/ShareBook.Service/Email/Templates/BookSentTemplate.html
- ShareBook/ShareBook.Test.Unit/Services/BookServiceTests.cs
Tarefa: https://trello.com/c/ZJxwDule/164-416-informar-o-recebimento-de-livro
Descrição: Para efetuar a refatoração para permitir que um usuário possa informar o recebimento de um livro, foi decido, através de reunião com o @raffacabofrio , que seria mais interessante criar um único endpoint para evitar segmentação de endpoints para atualizar o Status de um livro. Dessa forma, essa refatoração permite a atualização de Status que um usuário (Admin ou outros) teria permissão, alguns Status não são permitidos, visto que eles já são atribuídos automaticamente de acordo com a regra de negócio do projeto. 
Além disso, também implementei mais dois métodos para envio de e-mail, os quais são referentes aos Status "Sent" e "Received".
> Refatoração para criar um endpoint para permitir a atualização de Status do Livro

- ShareBook/ShareBook.Repository/Mapping/UserMap.cs
- ShareBook/ShareBook.Repository/Migrations/20200912230347_IndexUniqueEmail.Designer.cs
- ShareBook/ShareBook.Repository/Migrations/20200912230347_IndexUniqueEmail.cs
Um usuário reclamou que não estava conseguindo entrar e nem recuperar senha no Sharebook.
Após investigar reparei que o email dele estava duplicado no banco de dados. O que é bem estranho porque a gente trata isso no backend.
Além desse usuário haviam outros 11 usuários com o mesmo problema.
Eu suspeito que esse problema esteja relacionado com alguma indisponibilidade temporária do banco de dados. E alguma lógica de retry no EF. Porque em todos os casos as datas de criação eram iguais.
AÇÃO CORRETIVA
- Excluir manualmente os registros duplicados. *OK*
- Criar um índice unique no campo email. ( Essa PR )
> Add unique email index.

- ShareBook/ShareBook.Api/Controllers/BookController.cs
Ao tentar cadastrar um livro, não há verificação se a operação ocorreu como deveria, sempre retornando 200 e mensagem de sucesso.
Este pull request adiciona a verificação da propriedade ```Result.IsSuccess``` gerado pelo serviço, para que retorne 400 com a mensagem de erro quando necessário.
Exemplo de um POST de um livro inválido que retorna 200 mas não é cadastrado pois falha na validação de formato de imagem:
> {
>   "title": "Um livro aleatório",
>   "author": "Um autor desconhecido",
>   "categoryId": "B1A34609-A85C-4B36-893F-BA56AE911C2D",
>   "imageName": "string",
>   "imageBytes": "00000000",
>   "freightOption": "0",
>   "synopsis": "string",
>   "type": "1",
>   "eBookDownloadLink": "",
>   "eBookPdfFile": ""
> }
> Avaliar resultado antes de retornar ação create/update

- ShareBook/ShareBook.Api/Controllers/BookController.cs
- ShareBook/ShareBook.Domain/Enums/DonationStatus.cs
- ShareBook/ShareBook.Service/BookUser/BookUserService.cs
- ShareBook/ShareBook.Service/BookUser/IBookUserService.cs
Adiciona serviços e um endpoint para cancelamento do pedido do livro caso o usuário desista de concorrer à doação.
- Usuário cancela somente o próprio pedido
- Status da doação deve ser Aguardando ação do doador ou disponível
- Pedido não pode estar previamente cancelado.
> +Feature para cancelar pedidos

- ShareBook/ShareBook.Service/Upload/UploadService.cs
Checa se há outra imagem com o mesmo nome ao realizar upload, caso positivo adicionar data no formato Unix ao final do nome do arquivo.
> Checar se há imagem com o mesmo nome antes do upload

- ShareBook/ShareBook.Api/ViewModels/UpdateUserVM.cs
- ShareBook/ShareBook.Api/ViewModels/UserVM.cs
- ShareBook/ShareBook.Domain/DTOs/RegisterUserDTO.cs
- ShareBook/ShareBook.Domain/User.cs
- ShareBook/ShareBook.Domain/Validators/UserValidator.cs
- ShareBook/ShareBook.Repository/Mapping/UserMap.cs
- ShareBook/ShareBook.Repository/Migrations/20220923153450_Add_Instagram_Property.cs
- ShareBook/ShareBook.Repository/Migrations/ApplicationDbContextModelSnapshot.cs
- ShareBook/ShareBook.Service/User/UserService.cs
- ShareBook/ShareBook.Test.Unit/Mocks/UserMock.cs
1 - Adicionar propriedade Instagram no modelo User.cs;
2 - Referenciar a propriedade Instagram nos metodos Change(assinatura e corpo) e Anonymize(corpo) nas regras do modelo User.cs;
3 - Adicionar propriedade no DTO de User(RegisterUserDTO.cs);
4 - Adicionar regra de validacao de quantidade maxima de 100 caracteres para a propriedade Instagram no UserValidator.cs;
5 - Adicionar propriedade Instagram na chamada do metodo Change em UserService.cs
6 - Adicionar a propriedade Instagram do User no UserMap;
7 - Adicionar a propriedade Instagram no UserVM;
8 - Adicionar a propriedade Instagram no Context;
9 - Aterar o o mock de usuario adicionando o novo campo Instagram;
10 - Criar migration contendo o novo campo;
> Adicionar campo Instagram para usuário.

- ShareBook/ShareBook.Repository/Repository/Meetup/MeetupRepository.cs
Altera o método de ordenação do repositório dos meetups, assim temos sempre os mais recentes no topo da lista.
> Override no método de busca dos meetups do banco

- ShareBook/ShareBook.Api/Configuration/ServiceRepositoryCollectionExtensions.cs
- ShareBook/ShareBook.Api/Controllers/ContactUsController.cs
- ShareBook/ShareBook.Domain/Common/Result.cs
- ShareBook/ShareBook.Domain/ContactUs.cs
- ShareBook/ShareBook.Domain/DTOs/RegisterUserDTO.cs
- ShareBook/ShareBook.Domain/Validators/ContactUsValidator.cs
- ShareBook/ShareBook.Service/ContactUs/ContactUsService.cs
- ShareBook/ShareBook.Service/ContactUs/IContactUsService.cs
- ShareBook/ShareBook.Service/Recaptcha/IRecaptchaService.cs
- ShareBook/ShareBook.Service/Recaptcha/RecaptchaService.cs
- ShareBook/ShareBook.Service/User/UserService.cs
- ShareBook/ShareBook.Test.Unit/Services/ContactUsServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Services/RecaptchaServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Services/UserServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Validators/ContactUsValidatorTests.cs
feat: Creating IRecaptchaService + implementing simple validation of recaptcha to register, and update validation of recaptcha in contactUs (moving from FluentValidation to IRecaptchaService) + Unit tests.
Note: This will impact the validation on `ContactUs` endpoint.
Note: Depends => https://github.com/SharebookBR/sharebook-frontend/pull/438
> Add simple validation of recaptcha in register endpoint

- ShareBook/ShareBook.Service/Meetup/MeetupService.cs
Adiciona possibilidade de pesquisar por termos usados na descrição, como por exemplo pelo nome dos palestrantes.
> Add busca de meetup pela descrição

- .github/workflows/dotnet-build-validation.yml
- README.md
- ShareBook/ShareBook.Api/Dockerfile
- ShareBook/ShareBook.Api/ShareBook.Api.csproj
- ShareBook/ShareBook.Api/appsettings.json
- ShareBook/ShareBook.Domain/ShareBook.Domain.csproj
- ShareBook/ShareBook.Helper/ShareBook.Helper.csproj
- ShareBook/ShareBook.Infra.CrossCutting.Identity/ShareBook.Infra.CrossCutting.Identity.csproj
- ShareBook/ShareBook.Repository/ShareBook.Infra.Data.csproj
- ShareBook/ShareBook.Service/Muambator/MuambatorService.cs
- ShareBook/ShareBook.Service/ShareBook.Service.csproj
- ShareBook/ShareBook.Test.Unit/ShareBook.Test.Unit.csproj
- ShareBook/Sharebook.Jobs/Sharebook.Jobs.csproj
- Updated all projects from .Net 6 to .Net 8
- Updated All Nuget Packages to the latest version, except:
- `SixLabors.ImageSharp`: breaking changes
- `MailKit`: breaking changes
- `FluentValidation`: breaking changes
- `Rollbat` and `Rollbar.NetCore.AspNet`: breaking changes
- Removed deprecated package (`AutoMapper.Extensions.Microsoft.DependencyInjection`)
- Updated Dockerfile
- Updated Github Actions
> Upgrade from .Net 6 to .Net 8

- ShareBook/ShareBook.Api/Controllers/ContactUsController.cs
- ShareBook/ShareBook.Api/Controllers/MeetupController.cs
- ShareBook/ShareBook.Api/Controllers/OperationsController.cs
- ShareBook/ShareBook.Service/Book/BookService.cs
- ShareBook/ShareBook.Service/ContactUs/ContactUsEmailService.cs
- ShareBook/ShareBook.Service/ContactUs/ContactUsService.cs
- ShareBook/ShareBook.Service/ContactUs/IContactUsEmailService.cs
- ShareBook/ShareBook.Service/ContactUs/IContactUsService.cs
- ShareBook/ShareBook.Service/Meetup/IMeetupService.cs
- ShareBook/ShareBook.Service/Meetup/MeetupService.cs
- ShareBook/ShareBook.Service/Recaptcha/RecaptchaService.cs
- ShareBook/ShareBook.Service/Upload/IUploadService.cs
- ShareBook/ShareBook.Service/Upload/UploadService.cs
- ShareBook/ShareBook.Test.Unit/Jobs/MeetupSearchTests.cs
- ShareBook/ShareBook.Test.Unit/Services/BookServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Services/ContactUsEmailServiceTests.cs
- ShareBook/ShareBook.Test.Unit/Services/ContactUsServiceTests.cs
- ShareBook/ShareBook.Test.Unit/ShareBook.Test.Unit.csproj
The changes are made based on [.NET AsyncGuidance](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md).
- Turning endpoint of `ContactUsController` and `MeetupController` as async
- Got rid some warnings
- Adding unit test for `ContactUsEmailService. SendEmailContactUsAsync`
- Adding unit tests for `Jobs.MeetupSearchTests` ([MR 558](https://github.com/SharebookBR/sharebook-backend/pull/558))
> Turning endpoints of `ContactUsController` and `MeetupController` as async

- .github/workflows/postman-collection.yml
- ShareBook API - Tests.postman_collection.json
- ShareBook/ShareBook.Service/Email/EmailService.cs
With these updates we'll be able to manually trigger/start this job to check/validate if the dev environment is ok using our postman collection which is in the repository.
Note: I let the job as `workflow_dispatch` (to manually start it) because I'm not sure when a new version pushed to `develop` branch will be available at our dev environment (until I know we do the deployment to there outside the github actions)
---
As we discussed through our WhatsApp group, we need to change the `ImapPort`, but then we need to stablish the connection with `useSsl=false`, which was fixed as `true` in the source code. Now it'll get from `appsettings`.
> feat: Adding manual job "Postman collection validations" for dev environment + fix EmailService using ssl config

- ShareBook/.editorconfig
- ShareBook/ShareBook.sln
The intention of adding `.editorconfig` file (using the default example of Microsoft [ref](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/code-style-rule-options)) is to avoid fake changes when made from a different O.S (linux vs windows) and/or a different IDE.
> Adding .editorconfig file at solution level

- README.md
- ShareBook/ShareBook.Api/Startup.cs
- ShareBook/ShareBook.Repository/ShareBookSeeder.cs
- ShareBook/ShareBook.Test.Integration/GlobalUsings.cs
- ShareBook/ShareBook.Test.Integration/Setup/ShareBookTestsFixture.cs
- ShareBook/ShareBook.Test.Integration/Setup/ShareBookWebAppFactory.cs
- ShareBook/ShareBook.Test.Integration/ShareBook.Test.Integration.csproj
- ShareBook/ShareBook.Test.Integration/Tests/BookTests/BookTests.cs
- ShareBook/ShareBook.Test.Integration/Tests/CategoryTests/CategoryTests.cs
- ShareBook/ShareBook.Test.Integration/Tests/MeetupTests/MeetupTests.cs
- ShareBook/ShareBook.sln
- Built on top of [PR 570](https://github.com/SharebookBR/sharebook-backend/pull/570)
- Created a integration tests, using InMemory database (in the future we can use [Testcontainers for .NET](https://dotnet.testcontainers.org/) with the following tests:
- `Book`: `[GET] api/book/AvailableBooks_All`
- `Meetup`: 
- `[GET] api/Meetup?page={page}&pageSize={pageSize}&upcoming={upcoming}` (7x)
- `[GET] api/Meetup/search?criteria={criteria}` (3x)
- `Category`: `[GET] api/category`
All these new tests will be already executed on Github Action.
> Creating first few integration tests
